server:
  port: 8080
spring:
  application:
    name: my_java_demo
#  datasource:
#    url:  jdbc:mysql://127.0.0.1:3306/my_database?serverTimezone=GMT%2b8:00&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
#    username: root
#    password: 1234567890
#    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        file-extension: yml
        namespace: dev
      discovery:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        namespace: dev
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  typeAliasesPackage: org.example.myjavademo.dto